var annotated_dup =
[
    [ "xmlnode", null, [
      [ "CXmlNode", "classxmlnode_1_1_c_xml_node.html", "classxmlnode_1_1_c_xml_node" ]
    ] ],
    [ "CAboutDlg", "class_c_about_dlg.html", "class_c_about_dlg" ],
    [ "CActor", "class_c_actor.html", "class_c_actor" ],
    [ "CActorFactory", "class_c_actor_factory.html", "class_c_actor_factory" ],
    [ "CAnimChannel", "class_c_anim_channel.html", "class_c_anim_channel" ],
    [ "CAnimChannelAngle", "class_c_anim_channel_angle.html", "class_c_anim_channel_angle" ],
    [ "CAnimChannelPoint", "class_c_anim_channel_point.html", "class_c_anim_channel_point" ],
    [ "CBasket", "class_c_basket.html", "class_c_basket" ],
    [ "CBasketActual", "class_c_basket_actual.html", "class_c_basket_actual" ],
    [ "CBasketDrawable", "class_c_basket_drawable.html", "class_c_basket_drawable" ],
    [ "CBasketStandin", "class_c_basket_standin.html", "class_c_basket_standin" ],
    [ "CBug", "class_c_bug.html", "class_c_bug" ],
    [ "CBugActual", "class_c_bug_actual.html", "class_c_bug_actual" ],
    [ "CBugDemoDlg", "class_c_bug_demo_dlg.html", "class_c_bug_demo_dlg" ],
    [ "CBugDrawable", "class_c_bug_drawable.html", "class_c_bug_drawable" ],
    [ "CBugFactory", "class_c_bug_factory.html", "class_c_bug_factory" ],
    [ "CBugHead", "class_c_bug_head.html", "class_c_bug_head" ],
    [ "CBugImage", "class_c_bug_image.html", "class_c_bug_image" ],
    [ "CBugLibApp", "class_c_bug_lib_app.html", "class_c_bug_lib_app" ],
    [ "CBugPart", "class_c_bug_part.html", "class_c_bug_part" ],
    [ "CBugSeedDlg", "class_c_bug_seed_dlg.html", "class_c_bug_seed_dlg" ],
    [ "CBugStandin", "class_c_bug_standin.html", "class_c_bug_standin" ],
    [ "CBugVisitor", "class_c_bug_visitor.html", "class_c_bug_visitor" ],
    [ "CCanadianExperienceApp", "class_c_canadian_experience_app.html", "class_c_canadian_experience_app" ],
    [ "CDrawable", "class_c_drawable.html", "class_c_drawable" ],
    [ "CEye", "class_c_eye.html", "class_c_eye" ],
    [ "CHaroldFactory", "class_c_harold_factory.html", "class_c_harold_factory" ],
    [ "CHead", "class_c_head.html", "class_c_head" ],
    [ "CHeadTop", "class_c_head_top.html", "class_c_head_top" ],
    [ "CImageDrawable", "class_c_image_drawable.html", "class_c_image_drawable" ],
    [ "CLeg", "class_c_leg.html", "class_c_leg" ],
    [ "CPicture", "class_c_picture.html", "class_c_picture" ],
    [ "CPictureFactory", "class_c_picture_factory.html", "class_c_picture_factory" ],
    [ "CPictureObserver", "class_c_picture_observer.html", "class_c_picture_observer" ],
    [ "CPolyDrawable", "class_c_poly_drawable.html", "class_c_poly_drawable" ],
    [ "CPseudoRandom", "class_c_pseudo_random.html", "class_c_pseudo_random" ],
    [ "CRootSegment", "class_c_root_segment.html", "class_c_root_segment" ],
    [ "CRotatedBitmap", "class_c_rotated_bitmap.html", "class_c_rotated_bitmap" ],
    [ "CSegment", "class_c_segment.html", "class_c_segment" ],
    [ "CSpartyFactory", "class_c_sparty_factory.html", "class_c_sparty_factory" ],
    [ "CStinger", "class_c_stinger.html", "class_c_stinger" ],
    [ "CTimeline", "class_c_timeline.html", "class_c_timeline" ],
    [ "CTimelineDlg", "class_c_timeline_dlg.html", "class_c_timeline_dlg" ],
    [ "CViewEdit", "class_c_view_edit.html", "class_c_view_edit" ],
    [ "CViewTimeline", "class_c_view_timeline.html", "class_c_view_timeline" ]
];